### ISSUE TITLE
hackney 2.0 roadmap

### ISSUE THREAD

**Issue by benoitc** [benoitc/hackney#275]
Tasks for the hackney 2.0 version

- [ ] new manager to reuse connections #276
- [ ] full ipv6 support, eyeball strategy #206
- [ ] relax URL encoding #277
- [ ] improve proxy support
- [ ] improve HTTP 1.1 support

**Comment by edgurgel** [comment]
:+1:

**Comment by lazedo** [comment]
@benoitc Hi, maybe this would be a good time to introduce `min_pool_size` or `min_available`. sometimes there are a lot of simultaneous requests and i think we could benefit in performance if we had  `min_pool_size` connections ready. thoughts ?

**Comment by benoitc** [comment]
@lazedo how would it works? preconnecting resources? or something else?

**Comment by lazedo** [comment]
@benoitc yes, preconnecting resources and keep them alive

**Comment by benoitc** [comment]
@lazedo well there will be pre-connection, but keeping a minimum alive may create a network congestion. Servers don't like to have too much connections to them from the same origin. I add it to the todo list.
